[ClassVersion("1.0.1.0"), FriendlyName("VaultADDomainController")]
class xDSCVault_ADDomainController : OMI_BaseResource
{
    [Key] String DomainName;
    [Required, EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
    [Required, EmbeddedInstance("MSFT_Credential")] String SafemodeAdministratorPassword;
    [write] String DatabasePath;
    [write] String LogPath;
    [write] String SysvolPath;
    [write] String SiteName;
};
