[ClassVersion("1.0.1.0"), FriendlyName("VaultADDomainController")]
class xDSCVault_ADDomainController : OMI_BaseResource
{
    [Required, Description("Address of the Vault server")] String VaultAddress;
    [Write, Description("Version of the API to use")] String ApiPrefix;
    [Read, Description("Complete API path")] String ApiPath;    
    [Key] String DomainName;
    [Required, Description("Vault path to get the secret")] String SafemodeAdministratorPasswordVaultPath;
    [Required, Description("Domain Administrator username")] String DomainAdministratorUsername;
    [Required, Description("Vault path to get the secret")] String DomainAdministratorVaultPath;
    [write] String DatabasePath;
    [write] String LogPath;
    [write] String SysvolPath;
    [write] String SiteName;
};
